__author__ = 'jay'

CONTACT_TYPE_ADMIN = "Admin"
CONTACT_TYPE_PLAYER = "Player"

CONTACT_TYPE_CHOICES = (
    (CONTACT_TYPE_ADMIN,CONTACT_TYPE_ADMIN),
    (CONTACT_TYPE_PLAYER,CONTACT_TYPE_PLAYER)
)

GENDER_MALE = 'Male'
GENDER_FEMALE = 'Female'

GENDER_CHOICES = (
    (GENDER_MALE,GENDER_MALE),
    (GENDER_FEMALE,GENDER_FEMALE),
)

EVENT_TYPE_TOURNAMENT = 'Tournament'
EVENT_TYPE_REGULAR = 'Regular'

EVENT_TYPE_CHOICES = (
    (EVENT_TYPE_REGULAR,EVENT_TYPE_REGULAR),
    (EVENT_TYPE_TOURNAMENT,EVENT_TYPE_TOURNAMENT),
)