__author__ = 'jay'

GENDER_MALE = 'Male'
GENDER_FEMALE = 'Female'

GENDER_CHOICES = (
    (GENDER_MALE,GENDER_MALE),
    (GENDER_FEMALE,GENDER_FEMALE),
)

GAME_TYPE_TOURNAMENT = 'Tournament'
GAME_TYPE_REGULAR = 'Regular'

GAME_TYPE_CHOICES = (
    (GAME_TYPE_REGULAR,GAME_TYPE_REGULAR),
    (GAME_TYPE_TOURNAMENT,GAME_TYPE_TOURNAMENT),
)